name: hotline
grade: devel
version: v0.1.0
base: core18

license: MIT

summary: Open Links Faster

description: >
  hotline is a command-line tool that opens "parameterised" links.

confinement: devmode

parts:
  hotline:
    source: .
    plugin: nodejs
    nodejs-version: 14.3.0
    nodejs-package-manager: yarn
    build-packages: ['libcurl4-openssl-dev', 'git']

plugs:
  hotline-files:
    interface: personal-files
    read: [$HOME/.hotline]

apps:
  hotline:
    plugs:
      - home
      - hotline-files
      - network
      - desktop
    command: bin/hotline
