name: Hotline CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --global
    - run: npm run build --if-present

    - name: Test hotline exists
      run: which hl || exit 1

    - name: "Write config file"
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ${{ env.home}}/.hotline
        contents: |
          - id: "testid"
            url: "www.example.com"
        write-mode: append

    - name: "Run show command"
      run: hl --show | grep "www.example.com"
