name: Hotline CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --global
    - run: npm run build --if-present

    - name: "Write config file"
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: /home/runner/.hotline
        contents: |
          - id: "testid"
            url: "www.example.com"
        write-mode: append

    - name: "Test: is the short hotline alias installed?"
      run: which hl || exit 1

    - name: "Test: is the long hotline alias installed?"
      run: which hotline || exit 1

    - name: "Test: does --show print the site included in its config?"
      run: hl --show | grep "www.example.com"

    #- name: "Test: does an opened site print a URL?"
     # run: hl testid | grep "www.example.com"
   
    - name: "Test processes"
      run: "ps"
      
